---
#########################
#########################
## Golang Linter rules ##
#########################
#########################

# configure golangci-lint
# see https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml
run:
  # which dirs to skip: they won't be analyzed;
  skip-dirs:
    - gen
  skip-files:
    - lib/bad.go
issues:
  exclude:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
    - path: service
      linters:
        - errcheck
    - path: cmd
      linters:
        - errcheck
    - path: internal
      linters:
        - errcheck
linters:
  enable:
    - gosec
    - unconvert
    - gocyclo
    - goconst
    - gocritic
    - govet
    - revive
    - gofmt
    - prealloc
linters-settings:
  errcheck:
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: true
  govet:
    # report about shadowed variables
    check-shadowing: true
  gocyclo:
    # minimal code complexity to report, 30 by default
    min-complexity: 15
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
